### PR TITLE
add items.location.type value to aggregations

### PR DESCRIPTION
**Pull request by jamesgorrie**
Ref: https://github.com/wellcomecollection/platform/issues/4899

We'll add this, then move the frontend over, and remove locationType.

### CODE REVIEW

**Comment by jtweed** [comment]
Will this update the swagger automatically or is this one of things documented manually?

**Comment by jamesgorrie** [comment]
> Will this update the swagger automatically or is this one of things documented manually?

Swagger isn't generated automagically, but we have tests to make sure this PR won't pass, which I have updated

**Review by alexwlchan — APPROVED** [review]
This is failing cos a couple of expected error messages in tests need updating; I'm going to sort those out then get this merged.

**Comment by jamesgorrie** [comment]
Thanks @alexwlchan - sorry to leave it lingering.

**Pull request merged**
