### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by warrd**
Autoformat is failing on `master` builds.

### CODE REVIEW

**Review by jamesgorrie — APPROVED** [review]

**Review by jamieparkinson — CHANGES_REQUESTED** [review]
There are more than these 2 - let's fix them all at once. You can see them by running `make format && make lint` and/or copy them from my commit where I just saw the same issue https://github.com/wellcomecollection/catalogue/pull/962/commits/6b5a119a0d2ec904db5c0d9caf2ea251768ddf4c

**Comment by warrd** [comment]
@jamieparkinson have cherry picked that commit

**Review by jamieparkinson — APPROVED** [review]

**Review by jamesgorrie — COMMENTED** [review]
Does python linting not have `autofix`? Or have we not implemented it into the build?

**Comment by warrd** [comment]
The issue is that changes were pushed straight to `master`, and the autoformat build step does't have permission to push to `master` so fails.

**Comment by jamieparkinson** [comment]
PS I don't believe all of these changes were covered by the autofix capabilities

**Pull request merged**
