### PR TITLE
Fix ElasticRetrieverTest

### PR DESCRIPTION
**Pull request by warrd**

### CODE REVIEW

**Comment by alexwlchan** [comment]
Ah, is this to ensure there’s *something* in the index?

**Comment by warrd** [comment]
I'm not sure actually, this is from @jamieparkinson PR

**Comment by jamieparkinson** [comment]
The change that @alex.chan made caused it to throw on the assertion rather than failing how the test expects (and therefore not testing the thing that it claims to), so yeah, have to make sure there's something in the index

**Comment by warrd** [comment]
Can I get an approval for this?

**Review by jamieparkinson — APPROVED** [review]

**Pull request merged**
