### PR TITLE
Sorry

### PR DESCRIPTION
**Pull request by warrd**

### CODE REVIEW

**Review by jamesgorrie — APPROVED** [review]
✨

**Review by jamesgorrie — COMMENTED** [review]
Any reason not to use `info`?

**Comment by warrd** [comment]
@jamesgorrie yup cos we don't log `info` :see_no_evil:

**Comment by warrd** [comment]
I am trying connecting to the ES cluster locally rather than doing this, but might need to do this at a later point if that is not fruitful.

**Comment by jamesgorrie** [comment]
@warrd I am pretty certain we log info?
https://github.com/wellcomecollection/catalogue/blob/master/pipeline/id_minter/id_minter_works/src/main/resources/logback.xml#L14

**Comment by warrd** [comment]
Nope, none of it makes it through to kibana, I think we only pass through `warn` and above with firelens

**Pull request merged**
