### PR TITLE
Replace post-filtering & min_doc_count: 0 with global aggregations

### PR DESCRIPTION
**Pull request by jamieparkinson**
As per the advice in https://github.com/elastic/elasticsearch/issues/62084#issuecomment-689507644

Using the principles in https://github.com/wellcomecollection/docs/blob/master/adr/api_faceting.md I could identify where we did want to return empty buckets and where we didn't - this PR _does_ change some behaviours but I believe that these changes won't hit the UI as the now-removed buckets were already being filtered out. It also turns out there were some inconsistencies between image and works aggregations (oops!) which this fixes.

### CODE REVIEW

**Review by jamesgorrie — COMMENTED** [review]
It looks good, but just checking my understanding just trying to get an understanding of what the recommendation is.

Is it:
* you have an aggregation, unfiltered, with a sub aggregation filtered by a paired filter
* if there is a paired filter, we show the filtered aggregation, else the normal one

**Comment by jamieparkinson** [comment]
What do you mean by a "normal" aggregation?

**Comment by jamieparkinson** [comment]
We need to have filtered subaggregations in order _not_ to apply the same filters to the search and the aggregation buckets: we don't want aggregation buckets to be filtered by their paired filter.

This is achieved by doing a `global` aggregation in the case that a paired filter is present and applying all of the filters _except_ the paired one as subaggregations of the global parent aggregation.

If filtered aggregations are present then we always use them - the decisions about this are applied when the query is made, not when the response is parsed. The extra parsing logic here is just due to the fact that changing the queries changes the response format; you can summarise it as "use the most specific counts you can find in the response".

**Review by jamesgorrie — APPROVED** [review]

**Comment by jamesgorrie** [comment]
Thanks for explaining that @jamieparkinson.

**Pull request merged**
