### PR TITLE
add pipeline back and make errors use JSON

### PR DESCRIPTION
**Pull request by jamesgorrie**
While debugging this is useful. -means I won't have to go lookup the json, just copy it from the logs.

### CODE REVIEW

**Comment by warrd** [comment]
I'm not sure this can be applied, due to the fact that all the underlying infrastructure has changed?

**Comment by jamesgorrie** [comment]
@warrd I've already reapplied it as I tore it down by accident.

**Comment by warrd** [comment]
Ah so it's a new pipeline, just pointing to the old indices?

**Comment by jamesgorrie** [comment]
[The current API points to `04`](https://github.com/wellcomecollection/catalogue/blob/master/common/elasticsearch/src/main/scala/uk/ac/wellcome/elasticsearch/ElasticConfig.scala#L15)

So it needs to stay up and running till we fix the new one and move the API over.

I tore down the old pipeline by accident - so just making sure I don't do it again until the new one is prod and the API pointing at it.

**Comment by jamesgorrie** [comment]
Removed the logging as it wasn't compiling due to not having the right encoders, didn't fancy mucking around with it too much.

**Pull request merged**
